# Generated by Django 5.1.6 on 2025-05-22 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0003_birthdayimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
