# Generated by Django 5.1.6 on 2025-05-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0004_birthday_is_active_organization_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdayimport',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
