# Generated by Django 5.1.6 on 2026-04-25 09:51

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('birthdays', '0002_upgrade_import_schema'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='birthday',
            index=models.Index(fields=['organization', 'is_active'], name='birthday_bi_organiz_375546_idx'),
        ),
        migrations.AddIndex(
            model_name='birthday',
            index=models.Index(fields=['date_of_birth'], name='birthday_bi_date_of_03aab6_idx'),
        ),
        migrations.AddIndex(
            model_name='birthday',
            index=models.Index(django.db.models.functions.datetime.ExtractMonth('date_of_birth'), django.db.models.functions.datetime.ExtractDay('date_of_birth'), name='bday_month_day_idx'),
        ),
    ]
